server:
  port: 8081

spring:
  profiles:
    include: secret

  datasource:
    driver-class-name: ${DATASOURCE_DRIVER}
    url: ${DATASOURCE_URL}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false